title: Waiting Times Pi Display
description: A Raspberry Pi project that displays public transport waiting times, weather and overhead flights (and space stations) using an e-Paper display

# Theme configuration
theme: minima
show_downloads: false        # Hide the download buttons

# Site configuration
markdown: kramdown          # Markdown processor
kramdown:                   # Markdown options
  input: GFM               # GitHub Flavored Markdown
  hard_wrap: false         # Don't convert newlines to <br>

# Disable features we don't need
google_analytics: false     # Disable analytics
show_header: true          # Show the header section

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/